# default configurations ...
# https://jekyllrb.com/docs/configuration/default/
# tool icons at https://www.techicons.dev/icons


# site settings
url: https://github.com/maisygraves/blog
title: b-Log
description: documented projects, reflective write-ups and a curated collection of technical resources

# about me table
name: Maisy Graves
about-me: I analyze data to help make complex problems clearer, with an emphasis on careful reasoning and clear communication.

collections:
  skills:
    output: true
  tools:
    output: true

defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tools-page"
  - scope:
      path: ""
      type: "skills"
    values:
      layout: "skills-page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
    

